version: '3.1'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - $PWD/backup:/home/backup
      - persistent:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

volumes:
  persistent:
    external: true
